name: Codecov

on:
  push:
    branches: ["{{.DefaultBranch}}"]
  pull_request:
    branches: ["{{.DefaultBranch}}"]

permissions:
  contents: read

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage.out