name: Socket

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  pull-requests: write

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v4.1.7
      - name: Socket Security
        uses: SocketDev/action@937f824ec476dfd164d4a4d9995751427b0be143  # v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
